# Generated by Django 2.0.6 on 2018-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('fax', models.FileField(upload_to='')),
                ('fax_number', models.CharField(max_length=20)),
                ('test_field', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
