# Generated by Django 2.1 on 2018-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('fax', models.FileField(blank=True, null=True, upload_to='')),
                ('fax_number', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FaxNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
