# Generated by Django 2.0.5 on 2018-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_faxnumber_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faxnumber',
            name='campaign',
        ),
        migrations.AddField(
            model_name='faxnumber',
            name='campaign',
            field=models.ManyToManyField(to='product.Campaign'),
        ),
    ]
