# Generated by Django 2.0.5 on 2018-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180920_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedFaxNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
