# Generated by Django 2.1 on 2018-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180811_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaxNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
